site_name: PEOPLE-ECCO User Handbook
site_url: https://PEOPLE-ECCO.github.io
repo_name: PEOPLE-ECCO
repo_url: https://github.com/PEOPLE-ECCO

nav:
- Home: index.md
- Introduction:
    - PEOPLE-ECCO Solutions: 'solutions.md'
    - PEOPLE-ECCO Platform: 'platform.md'
- Solution Handbook:
  - Terrestrial Solutions: 
    - Vegetation Productivity Trend (VPT):
      - Theoretical Background: 'handbook/terrestrial-solutions/VPT/theoretical-background.md'
      - Key Considerations: 'handbook/terrestrial-solutions/VPT/key-considerations.md'
      - Getting-Started: 'handbook/terrestrial-solutions/VPT/getting-started.md'
    - Disturbance Occurrence:
      - Theoretical Background: 'handbook/terrestrial-solutions/disturbance-occurrence/theoretical-background.md'
      - Key Considerations: 'handbook/terrestrial-solutions/disturbance-occurrence/key-considerations.md'
      - Getting-Started: 'handbook/terrestrial-solutions/disturbance-occurrence/getting-started.md'
    - Habitat Disturbance:
      - Theoretical Background: 'handbook/terrestrial-solutions/habitat-disturbance/theoretical-background.md'
      - Key Considerations: 'handbook/terrestrial-solutions/habitat-disturbance/key-considerations.md'
      - Getting-Started: 'handbook/terrestrial-solutions/habitat-disturbance/getting-started.md'
  - Marine Solutions:
    - Submerged Aquatic Vegetation (SAV):
      - Theoretical Background: 'handbook/marine-solutions/SAV/theoretical-background.md'
      - Key Considerations: 'handbook/marine-solutions/SAV/key-considerations.md'
      - Getting-Started: 'handbook/marine-solutions/SAV/getting-started.md'
    - Marine Habitat Frequency:
      - Theoretical Background: 'handbook/marine-solutions/habitat-frequency/theoretical-background.md'
      - Key Considerations: 'handbook/marine-solutions/habitat-frequency/key-considerations.md'
      - Getting-Started: 'handbook/marine-solutions/habitat-frequency/getting-started.md'
    - Marine Habitat Connectivity:
      - Theoretical Background: 'handbook/marine-solutions/habitat-connectivity/theoretical-background.md'
      - Key Considerations: 'handbook/marine-solutions/habitat-connectivity/key-considerations.md'
      - Getting-Started: 'handbook/marine-solutions/habitat-connectivity/getting-started.md'
- Solutions Integration: 'integration/integration-interoperability.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme: 
  name: material
  features: 
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra_css:
  - stylesheets/extra.css
  - stylesheets/mkdocstrings.css